### ISSUE TITLE
Account Creation

### ISSUE THREAD

**Issue by Karnith** [ryancp/sailng#11]
You probably know this, but the password character string number is set to minimum 8 yet still creates users and logs them in when password is under 8 characters. Users can post messages, but when they log out they can't log in due to passport not creating the password (cause it's under 8 characters). I would suggest having a check in place that prohibits the creation of users until all criteria is met for account creation. Maybe a beforeCreate method in the model?

**Comment by ryancp** [comment]
This should be fixed by a recent commit.
