### ISSUE TITLE
blank browser

### ISSUE THREAD

**Issue by antoniosap** [ryancp/sailng#17]
i follow (on sails 0.10.5)
    $ npm install
    $ cd assets
    $ bower install
    $ cd ../
    $ sails lift

load page, html present, no display. any ideas ?

**Comment by ahaus** [comment]
AngularJS (1.3.x) asks for a base tag. 
I just added <base href="/"> in layout.ejs just after the <head> tag. 
As an alternative you might set requireBase() to false with $locastion.requireBase(false).
See: https://docs.angularjs.org/guide/$location

**Comment by ryancp** [comment]
This has been fixed by most recent commit.
