### ISSUE TITLE
Invalid usage of user`publishAdd(...)`

### ISSUE THREAD

**Issue by blah238** [ryancp/sailng#8]
I went through and changed all instances of `.done` to `.exec` as described in https://github.com/ryancp/sailng/issues/5.

When running the sailng app and entering messages, the following error appears in the node console, but everything appears to still operate correctly (messages appear on all connected clients).

```error: Invalid usage of user`publishAdd(id, alias, isAdded, [socketToOmit])````

Any ideas what this is about?

**Comment by ryancp** [comment]
This should be fixed by a recent commit.
